# permissions for end users to view mysqlrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mysqlrestore-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mysql-operator
    app.kubernetes.io/part-of: mysql-operator
    app.kubernetes.io/managed-by: kustomize
  name: mysqlrestore-viewer-role
rules:
- apiGroups:
  - batch.alongparty.cn
  resources:
  - mysqlrestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.alongparty.cn
  resources:
  - mysqlrestores/status
  verbs:
  - get
